apps:
  - name: pm2-exercise
    script: ./src/index.js
    watch: ["src"]
    exec_mode: cluster
    instances: max
    max_memory_restart: 100M
    env_dev:
      NODE_ENV: development
    env_prod:
      NODE_ENV: production